language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '14'
  - '12'
install:
  - npm install --ignore-engines
script:
  - npm run prepublishOnly
after_success:
  - npm run codecov
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
